/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlarmGroup: typeof import('./components/layout/AlarmGroup.vue')['default']
    AlarmListDialog: typeof import('./components/layout/AlarmListDialog.vue')['default']
    AlarmPill: typeof import('./components/layout/AlarmPill.vue')['default']
    AppLayout: typeof import('./components/layout/AppLayout.vue')['default']
    AssetTrendChart: typeof import('./components/charts/AssetTrendChart.vue')['default']
    BarChart: typeof import('./components/charts/BarChart.vue')['default']
    DataListCard: typeof import('./components/ui/DataListCard.vue')['default']
    DonutChart: typeof import('./components/charts/DonutChart.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    EmptyState: typeof import('./components/ui/EmptyState.vue')['default']
    FormDialog: typeof import('./components/ui/FormDialog.vue')['default']
    LineChart: typeof import('./components/charts/LineChart.vue')['default']
    LoadingCard: typeof import('./components/ui/LoadingCard.vue')['default']
    MetricCard: typeof import('./components/ui/MetricCard.vue')['default']
    MoneyDisplay: typeof import('./components/ui/MoneyDisplay.vue')['default']
    Navbar: typeof import('./components/layout/Navbar.vue')['default']
    PageHeader: typeof import('./components/ui/PageHeader.vue')['default']
    PieChart: typeof import('./components/charts/PieChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionHeader: typeof import('./components/ui/SectionHeader.vue')['default']
    Sidebar: typeof import('./components/layout/Sidebar.vue')['default']
    SidebarContent: typeof import('./components/layout/SidebarContent.vue')['default']
    SidebarNavButton: typeof import('./components/layout/SidebarNavButton.vue')['default']
    StatusBadge: typeof import('./components/ui/StatusBadge.vue')['default']
    TrendBadge: typeof import('./components/ui/TrendBadge.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
