/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./components/layout/AppLayout.vue')['default']
    BarChart: typeof import('./components/charts/BarChart.vue')['default']
    DataListCard: typeof import('./components/ui/DataListCard.vue')['default']
    DonutChart: typeof import('./components/charts/DonutChart.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    EmptyState: typeof import('./components/ui/EmptyState.vue')['default']
    FormDialog: typeof import('./components/ui/FormDialog.vue')['default']
    LineChart: typeof import('./components/charts/LineChart.vue')['default']
    LoadingCard: typeof import('./components/ui/LoadingCard.vue')['default']
    MetricCard: typeof import('./components/ui/MetricCard.vue')['default']
    MoneyDisplay: typeof import('./components/ui/MoneyDisplay.vue')['default']
    Navbar: typeof import('./components/layout/Navbar.vue')['default']
    PageHeader: typeof import('./components/ui/PageHeader.vue')['default']
    PieChart: typeof import('./components/charts/PieChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionHeader: typeof import('./components/ui/SectionHeader.vue')['default']
    Sidebar: typeof import('./components/layout/Sidebar.vue')['default']
    SidebarContent: typeof import('./components/layout/SidebarContent.vue')['default']
    SidebarNavButton: typeof import('./components/layout/SidebarNavButton.vue')['default']
    StatusBadge: typeof import('./components/ui/StatusBadge.vue')['default']
    TrendBadge: typeof import('./components/ui/TrendBadge.vue')['default']
  }
}
