"""Asset domain SQLModel tables + CRUD schemas."""
from app.models.assets.estate import (
    Estate,
    EstateCreate,
    EstateJournal,
    EstateJournalCreate,
    EstateJournalRead,
    EstateJournalUpdate,
    EstateRead,
    EstateUpdate,
)
from app.models.assets.insurance import (
    Insurance,
    InsuranceCreate,
    InsuranceJournal,
    InsuranceJournalCreate,
    InsuranceJournalRead,
    InsuranceJournalUpdate,
    InsuranceRead,
    InsuranceUpdate,
)
from app.models.assets.loan import (
    Loan,
    LoanCreate,
    LoanJournal,
    LoanJournalCreate,
    LoanJournalRead,
    LoanJournalUpdate,
    LoanRead,
    LoanUpdate,
)
from app.models.assets.other_asset import (
    OtherAsset,
    OtherAssetCreate,
    OtherAssetRead,
    OtherAssetUpdate,
)
from app.models.assets.stock import (
    StockDetail,
    StockDetailCreate,
    StockDetailRead,
    StockDetailUpdate,
    StockJournal,
    StockJournalCreate,
    StockJournalRead,
    StockJournalUpdate,
)
from app.models.assets.stock_category import (
    StockCategory,
    StockCategoryCreate,
    StockCategoryRead,
    StockCategoryUpdate,
)

__all__ = [
    "Estate",
    "EstateCreate",
    "EstateJournal",
    "EstateJournalCreate",
    "EstateJournalRead",
    "EstateJournalUpdate",
    "EstateRead",
    "EstateUpdate",
    "Insurance",
    "InsuranceCreate",
    "InsuranceJournal",
    "InsuranceJournalCreate",
    "InsuranceJournalRead",
    "InsuranceJournalUpdate",
    "InsuranceRead",
    "InsuranceUpdate",
    "Loan",
    "LoanCreate",
    "LoanJournal",
    "LoanJournalCreate",
    "LoanJournalRead",
    "LoanJournalUpdate",
    "LoanRead",
    "LoanUpdate",
    "OtherAsset",
    "OtherAssetCreate",
    "OtherAssetRead",
    "OtherAssetUpdate",
    "StockDetail",
    "StockDetailCreate",
    "StockDetailRead",
    "StockDetailUpdate",
    "StockJournal",
    "StockJournalCreate",
    "StockJournalRead",
    "StockJournalUpdate",
    "StockCategory",
    "StockCategoryCreate",
    "StockCategoryRead",
    "StockCategoryUpdate",
]
