"""add card_expiry to Credit_Card

Revision ID: 2ac6bdb555b5
Revises: 42adcdf00d6d
Create Date: 2026-05-23 11:20:36.351640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2ac6bdb555b5'
down_revision: Union[str, Sequence[str], None] = '42adcdf00d6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Credit_Card', sa.Column('card_expiry', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Credit_Card', 'card_expiry')
    # ### end Alembic commands ###
