"""BE-011 add parent_id to Code_Data

Revision ID: 42adcdf00d6d
Revises: cc79a1790004
Create Date: 2026-04-25 11:27:08.354024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '42adcdf00d6d'
down_revision: Union[str, Sequence[str], None] = 'cc79a1790004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Code_Data', sa.Column('parent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Code_Data', 'parent_id')
    # ### end Alembic commands ###
