"""BE-007 monthly_report domain tables

Revision ID: 4798a18d11d3
Revises: ad1046ef6fcf
Create Date: 2026-04-24 21:48:17.376154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4798a18d11d3'
down_revision: Union[str, Sequence[str], None] = 'ad1046ef6fcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Account_Balance',
    sa.Column('vesting_month', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('fx_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fx_rate', sa.Float(), nullable=False),
    sa.Column('is_calculate', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('vesting_month', 'id')
    )
    op.create_table('Credit_Card_Balance',
    sa.Column('vesting_month', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('fx_rate', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('vesting_month', 'id')
    )
    op.create_table('Estate_Net_Value_History',
    sa.Column('vesting_month', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('market_value', sa.Float(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('estate_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('vesting_month', 'id', 'asset_id')
    )
    op.create_table('Insurance_Net_Value_History',
    sa.Column('vesting_month', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('surrender_value', sa.Float(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('fx_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fx_rate', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('vesting_month', 'id', 'asset_id')
    )
    op.create_table('Journal',
    sa.Column('distinct_number', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vesting_month', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('spend_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('spend_way', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('spend_way_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('spend_way_table', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action_main', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action_main_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action_main_table', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action_sub', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('action_sub_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('action_sub_table', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('spending', sa.Float(), nullable=False),
    sa.Column('invoice_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('distinct_number')
    )
    op.create_table('Loan_Balance',
    sa.Column('vesting_month', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('vesting_month', 'id')
    )
    op.create_table('Stock_Net_Value_History',
    sa.Column('vesting_month', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stock_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stock_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('fx_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fx_rate', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('vesting_month', 'id', 'asset_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Stock_Net_Value_History')
    op.drop_table('Loan_Balance')
    op.drop_table('Journal')
    op.drop_table('Insurance_Net_Value_History')
    op.drop_table('Estate_Net_Value_History')
    op.drop_table('Credit_Card_Balance')
    op.drop_table('Account_Balance')
    # ### end Alembic commands ###
