"""change Target_Setting.setting_value to str

Revision ID: 87622acdcc6c
Revises: cbe794bb79ba
Create Date: 2026-05-23 14:46:48.606655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '87622acdcc6c'
down_revision: Union[str, Sequence[str], None] = 'cbe794bb79ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Target_Setting', 'setting_value',
               existing_type=sa.FLOAT(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=45),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Target_Setting', 'setting_value',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=45),
               type_=sa.FLOAT(),
               existing_nullable=False)
    # ### end Alembic commands ###
