"""BE-006 settings domain tables

Revision ID: ad1046ef6fcf
Revises: 4754cf2b6306
Create Date: 2026-04-24 21:42:51.729539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ad1046ef6fcf'
down_revision: Union[str, Sequence[str], None] = '4754cf2b6306'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fx_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_calculate', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('in_use', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=False),
    sa.Column('memo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('owner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('account_index', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Account_account_id'), 'Account', ['account_id'], unique=True)
    op.create_table('Alarm',
    sa.Column('alarm_id', sa.Integer(), nullable=False),
    sa.Column('alarm_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('alarm_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('due_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('alarm_id')
    )
    op.create_table('Code_Data',
    sa.Column('code_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code_group', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('code_group_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('in_use', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code_index', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('code_id')
    )
    op.create_table('Credit_Card',
    sa.Column('credit_card_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('card_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('card_no', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_day', sa.Integer(), nullable=True),
    sa.Column('charge_day', sa.Integer(), nullable=True),
    sa.Column('limit_date', sa.Integer(), nullable=True),
    sa.Column('feedback_way', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fx_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('in_use', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('credit_card_index', sa.Integer(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('credit_card_id')
    )
    op.create_table('Budget',
    sa.Column('budget_year', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expected01', sa.Float(), nullable=False),
    sa.Column('expected02', sa.Float(), nullable=False),
    sa.Column('expected03', sa.Float(), nullable=False),
    sa.Column('expected04', sa.Float(), nullable=False),
    sa.Column('expected05', sa.Float(), nullable=False),
    sa.Column('expected06', sa.Float(), nullable=False),
    sa.Column('expected07', sa.Float(), nullable=False),
    sa.Column('expected08', sa.Float(), nullable=False),
    sa.Column('expected09', sa.Float(), nullable=False),
    sa.Column('expected10', sa.Float(), nullable=False),
    sa.Column('expected11', sa.Float(), nullable=False),
    sa.Column('expected12', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['category_code'], ['Code_Data.code_id'], ),
    sa.PrimaryKeyConstraint('budget_year', 'category_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Budget')
    op.drop_table('Credit_Card')
    op.drop_table('Code_Data')
    op.drop_table('Alarm')
    op.drop_index(op.f('ix_Account_account_id'), table_name='Account')
    op.drop_table('Account')
    # ### end Alembic commands ###
