"""BE-008 assets domain tables

Revision ID: afbbbd7a1e61
Revises: 4798a18d11d3
Create Date: 2026-04-25 10:58:28.862816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'afbbbd7a1e61'
down_revision: Union[str, Sequence[str], None] = '4798a18d11d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Estate',
    sa.Column('estate_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estate_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estate_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estate_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('obtain_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('loan_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estate_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('memo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('estate_id')
    )
    op.create_table('Estate_Journal',
    sa.Column('distinct_number', sa.Integer(), nullable=False),
    sa.Column('estate_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estate_excute_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('excute_price', sa.Float(), nullable=False),
    sa.Column('excute_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('memo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('distinct_number')
    )
    op.create_table('Insurance',
    sa.Column('insurance_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('insurance_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('in_account', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('out_account', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('end_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pay_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pay_day', sa.Integer(), nullable=False),
    sa.Column('expected_spend', sa.Float(), nullable=False),
    sa.Column('has_closed', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('insurance_id')
    )
    op.create_table('Insurance_Journal',
    sa.Column('distinct_number', sa.Integer(), nullable=False),
    sa.Column('insurance_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('insurance_excute_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('excute_price', sa.Float(), nullable=False),
    sa.Column('excute_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('memo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('distinct_number')
    )
    op.create_table('Loan',
    sa.Column('loan_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('loan_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('loan_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('apply_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('grace_expire_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pay_day', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('repayed', sa.Float(), nullable=False),
    sa.Column('loan_index', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('loan_id')
    )
    op.create_table('Loan_Journal',
    sa.Column('distinct_number', sa.Integer(), nullable=False),
    sa.Column('loan_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('loan_excute_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('excute_price', sa.Float(), nullable=False),
    sa.Column('excute_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('memo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('distinct_number')
    )
    op.create_table('Other_Asset',
    sa.Column('asset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asset_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asset_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vesting_nation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('in_use', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asset_index', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_table('Stock_Detail',
    sa.Column('distinct_number', sa.Integer(), nullable=False),
    sa.Column('stock_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('excute_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('excute_amount', sa.Float(), nullable=False),
    sa.Column('excute_price', sa.Float(), nullable=False),
    sa.Column('excute_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('memo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('distinct_number')
    )
    op.create_table('Stock_Journal',
    sa.Column('stock_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stock_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stock_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expected_spend', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('stock_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Stock_Journal')
    op.drop_table('Stock_Detail')
    op.drop_table('Other_Asset')
    op.drop_table('Loan_Journal')
    op.drop_table('Loan')
    op.drop_table('Insurance_Journal')
    op.drop_table('Insurance')
    op.drop_table('Estate_Journal')
    op.drop_table('Estate')
    # ### end Alembic commands ###
