"""change Insurance.pay_day to str

Revision ID: cbe794bb79ba
Revises: 2ac6bdb555b5
Create Date: 2026-05-23 11:30:11.320584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cbe794bb79ba'
down_revision: Union[str, Sequence[str], None] = '2ac6bdb555b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Insurance', 'pay_day',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=23),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Insurance', 'pay_day',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=23),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
