"""BE-009 dashboard domain tables

Revision ID: cc79a1790004
Revises: afbbbd7a1e61
Create Date: 2026-04-25 11:01:23.922954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cc79a1790004'
down_revision: Union[str, Sequence[str], None] = 'afbbbd7a1e61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FX_Rate',
    sa.Column('import_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('buy_rate', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('import_date', 'code')
    )
    op.create_table('Stock_Price_History',
    sa.Column('stock_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fetch_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('highest_price', sa.Float(), nullable=False),
    sa.Column('lowest_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('stock_code', 'fetch_date')
    )
    op.create_table('Target_Setting',
    sa.Column('distinct_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_year', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('setting_value', sa.Float(), nullable=False),
    sa.Column('is_done', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('distinct_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Target_Setting')
    op.drop_table('Stock_Price_History')
    op.drop_table('FX_Rate')
    # ### end Alembic commands ###
